services:
  # 1. FastAPI Web Server (Connected Live to Neon Cloud PostgreSQL & Upstash Redis)
  - type: web
    name: skipd-commerce-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGINS
        value: "*"
      - key: DATABASE_URL
        value: postgresql+asyncpg://neondb_owner:npg_co6MJSXeWK8z@ep-still-king-axcdr7h1-pooler.c-4.us-east-2.aws.neon.tech/neondb?ssl=require
      - key: REDIS_URL
        value: rediss://default:gQAAAAAAApeoAAIgcDIyYmVlZDhhODBhY2Q0MjhiYmUzYzkzMzlkNDY3N2ZiYw@relaxed-beetle-169896.upstash.io:6379
      - key: JWT_SECRET
        value: super_secret_jwt_key_skipd_2026_dev
      - key: RAZORPAY_KEY_ID
        value: rzp_test_TPfRXRqzrh7kXX
      - key: RAZORPAY_KEY_SECRET
        value: EwSRHUOV8KNJrsQ49U53kPtA
      - key: SHIPROCKET_EMAIL
        value: demo@skipd.in
      - key: SHIPROCKET_PASSWORD
        value: demo_password_123
